In [2]:
import numpy as np

In [3]:
z = np.array([1,2,3,4,5])
z

array([1, 2, 3, 4, 5])

In [4]:
lista = ['batata', 'arroz','feixão']
lista2 = [1,2,3,4]
lista
lista2

[1, 2, 3, 4]

In [5]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(type(a))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [6]:
zeros = np.zeros(shape = (5,6,6))
print(zeros)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [7]:
uns = np.ones(shape = (5,3,3))
print(uns)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [8]:
passos = np.arange(step = 1,start = 50, stop = 56)
print(passos)

[50 51 52 53 54 55]


In [11]:
ar_linear = np.linspace(0,100, num = 10, endpoint = True)
print(ar_linear)
print(ar_linear.sum())
print(ar_linear.mean())
print(ar_linear.max())
print(ar_linear.min())

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
500.0
50.0
100.0
0.0


In [10]:
print(zeros.shape)
print(zeros.ndim)
print(zeros.size)

(5, 6, 6)
3
180


In [15]:
print(uns.sum())
print(uns.shape)

45.0
(5, 3, 3)
