In [ ]:
lista1 = [1,2,3,4]
lista2 = [5,6,7,8]
lista3 = ['batata','arroz','feijao']

In [ ]:
matriz = [lista1,lista2,lista3]
matriz

In [ ]:
len(matriz)

In [ ]:
matriz[2][0]

In [ ]:
calc = 24*60
dia = range(0,calc)
lst=[x for x in dia]
lst 

In [ ]:
import numpy as np
a = np.zeros(10)
type(a[0])


In [10]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
x = np.empty(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
z.shape


(10,)

In [15]:
z.shape=(10,1)

z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [16]:
z = np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
z = np.empty(3)
type(z[1])

numpy.float64

In [24]:
z = np.linspace(4,10,5)
z

array([ 4. ,  5.5,  7. ,  8.5, 10. ])

In [26]:
z = np.array([10,20])
z

array([10, 20])

In [27]:
n_list = [1,2,3,4,5]
z = np.array([n_list])
z

array([[1, 2, 3, 4, 5]])